box      = 'ubuntu/trusty64'
hostname = 'simple.local'

Vagrant.configure('2') do |config|
  config.vm.box = box
  config.vm.hostname = hostname

  config.vm.provision :shell do |shell|
    shell.path = 'puppet/librarian.sh'
    shell.args = '-g'
  end

  config.vm.provision 'puppet' do |puppet|
    puppet.manifests_path = 'puppet/manifests'
  end
end
